<!DOCTYPE html>
	<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		
		<title><?php echo $this->title;?></title>
	</head>
	<body>
		<h1><?php echo $this->title;?></h1>
		<p><?php echo $this->message;?></p>
		<ul>
			<li><a href="<?php echo $this->_helper->url(array("controller"=>"hello-world"))?>">Hello World Page</a></li>
			<li><a href="http://github.com/evandrobalmant/jiraya-mvc" target="_blank">Github Project</a></li>
		</ul>
	</body>
</html>